MMORPGBB/urls.py

from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

from board.views import IndexView

urlpatterns = [
    path('', IndexView.as_view()),
    path('admin/', admin.site.urls),
    path('board/', include('board.urls')),
    path('auth/', include('sign.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

board/urls.py
from django.urls import path

from .views import *

app_name = 'board'
urlpatterns = [
    #article
    path('', ArticleList.as_view(), name='article_list'),
    path('<int:pk>', ArticleDetail.as_view(), name='article_detail'),
    path('create/', ArticleCreate.as_view(), name='article_create'),
    path('update/<int:article_pk>', ArticleUpdate.as_view(), name='article_update'),
    path('<int:article_pk>/delete/', ArticleDelete.as_view(), name='article_delete'),
    #response
    path('<int:article_pk>/response', ResponseList.as_view(), name='response_list'),
    path('<int:article_pk>/create_Response', ResponseCreate.as_view(), name='response_create'),
    path('<int:article_pk>/response/<int:response_pk>/accept', ResponseAccept.as_view(), name='response_accept'),
    path('<int:article_pk>/response/<int:response_pk>/reject', ResponseReject.as_view(), name='response_reject'),
    path('response/<int:response_pk>/delete', ResponseDelete.as_view(), name='response_delete'),
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
    #views  
    path('category/<slug:name>', CategoryView.as_view(), name='category'),
    path('by_author/<slug:name>', ByAuthorView.as_view(), name='by_author'),

]

sign/urls.py
from django.urls import path, include


urlpatterns = [
    path('', include('allauth.urls')),
]

board/models.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.contrib.auth import get_user_model
from django.db import models


User = get_user_model()

class Category(models.Model):
    name = models.CharField(max_length=32, unique=True)

    def __str__(self):
        return f'{self.name}'


class Article(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Author')
    dateCreation = models.DateTimeField(auto_now_add=True)
    title = models.CharField('Title', max_length=128)
    text = RichTextUploadingField('Text')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Category')

    def __str__(self):
        return f'{self.title}'


class Response(models.Model):
    author = models.OneToOneField(User, on_delete=models.CASCADE)
    text = models.TextField(max_length=1536)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    approved = models.BooleanField('Approved', null=True, blank=True)
    dateCreation = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.author}'
    #- {self.datetime}

board/forms.py
from ckeditor_uploader.widgets import CKEditorUploadingWidget
from django import forms

from .models import *


class ArticleCreateForm(forms.ModelForm):
    category = forms.ModelChoiceField(
        label='Category',
        widget=forms.Select(attrs={'class': 'form-select'}),
        queryset=Category.objects.all()
    )
    title = forms.CharField(label='Title', widget=forms.TextInput(attrs={'class': 'form-control'}))
    text = forms.CharField(label='Text', widget=CKEditorUploadingWidget(attrs={'class': 'form-control'}))

#    class Meta:
#        model = Article
#        exclude = ('author',)


class ResponseCreateForm(forms.ModelForm):
    text = forms.CharField(label='Text', widget=forms.Textarea(attrs={'class': 'form-control'}))

    class Meta:
        model = Response
        fields = ('text',)

board/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
# from django.core.mail import EmailMultiAlternatives
from django.shortcuts import render, redirect
# from django.template.loader import render_to_string
from django.urls import reverse
from django.views import View
from django.views.generic import ListView, CreateView, UpdateView, DetailView, DeleteView, TemplateView

from .forms import ArticleCreateForm, ResponseCreateForm
from .models import *
from .utils.permissions import IsAuthorMixin, NotIsAuthorMixin


class IndexView(LoginRequiredMixin, TemplateView):
    template_name = 'board/front.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        return context


class ArticleList(ListView):
    model = Article
    context_object_name = 'article_list'
    queryset = Article.objects.order_by('dateCreation')


class ArticleDetail(DetailView):
    model = Article
    context_object_name = 'article'


class ArticleCreate(LoginRequiredMixin, CreateView):
    model = Article
    form_class = ArticleCreateForm
    template_name = 'board/crud/article_create.html'

    def get_success_url(self):
        return reverse('board:article_list')

    def form_valid(self, form):
        article = form.save(commit=False)
        user = self.request.user
        article.author = user
        return super().form_valid(form)


class ArticleUpdate(IsAuthorMixin, UpdateView):
    model = Article
    pk_url_kwarg = 'Article_pk'
    form_class = ArticleCreateForm
    template_name = 'board/crud/article_create.html'

    def get_success_url(self):
        return reverse('board:article_list')

    def form_valid(self, form):
        messages.success(self.request, 'Success!')
        return super().form_valid(form)


class ArticleDelete(LoginRequiredMixin, DeleteView):
    model = Article
    template_name = 'board/crud/article_delete.html'
    success_url = '/board/'
    permission_required = 'board.article_delete'
    context_object_name = 'article'

    def get_object(self, **kwargs):
        article_id = self.kwargs.get('article_pk')
        article = Article.objects.get(pk=article_id)
        return article


class ResponseList(IsAuthorMixin, View):
    def get(self, request, *args, **kwargs):
        article_pk = kwargs['article_pk']
        article = Article.objects.get(pk=article_pk)
        rp = Response.objects.order_by('dateCreation').filter(article=article)

        context = {
            'response': rp,
            'article': article
        }

        return render(request, 'board/response_list.html', context)


class ResponseCreate(NotIsAuthorMixin, View):
    def get(self, request, **kwargs):
        form = ResponseCreateForm(request.ARTICLE or None)
        article = Article.objects.get(pk=kwargs['article_pk'])

        context = {
            'form': form,
            'article': article
        }

        return render(request, 'board/crud/response_create.html', context)

    def article(self, request, *args, **kwargs):
        form = ResponseCreateForm(request.ARTICLE)
        user = request.user
        article_pk = kwargs['article_pk']

        if form.is_valid():
            response = form.save(commit=False)
            response.author = user
            response.article = Article.objects.get(pk=article_pk)
            response.save()

        return redirect('board:article_list')


class ResponseAccept(IsAuthorMixin, View):
    def get(self, request, *args, **kwargs):
        response_pk = kwargs['response_pk']

        response = Response.objects.get(pk=response_pk)
        response.approved = True
        response.save()

        return redirect(request.META['HTTP_REFERER'])


class ResponseReject(IsAuthorMixin, View):
    def get(self, request, *args, **kwargs):
        response_pk = kwargs['response_pk']

        response = Response.objects.get(pk=response_pk)
        response.approved = False
        response.save()

        return redirect(request.META['HTTP_REFERER'])


class ResponseDelete(LoginRequiredMixin, DeleteView):
    model = Response
    template_name = 'board/crud/response_delete.html'
    success_url = '/board/'
    permission_required = ('board.response_delete')
    context_object_name = 'response'

    def get_object(self, **kwargs):
        response_id = self.kwargs.get('response_pk')
        response = Response.objects.get(pk=response_id)
        return response


class DashboardView(View):
    def get(self, request, *args, **kwargs):
        context = {
            'article': request.user.article_set.all(),
        }
        return render(request, 'board/dashboard.html', context)


class CategoryView(ListView):
    def get(self, request, *args, **kwargs):
        category = Category.objects.get(name=kwargs['name'])
        ar = Article.objects.order_by('dateCreation').filter(category=category)

        context = {
            'category': category,
            'article': ar,
        }

        return render(request, 'board/category_list.html', context)


class ByAuthorView(ListView):
    def get(self, request, *args, **kwargs):
        author = User.objects.get(username=kwargs['name'])
        ar = Article.objects.order_by('dateCreation').filter(author=author)

        context = {
            'author': author,
            'article': ar,
        }

        return render(request, 'board/by_author.html', context)

board/templates/board/includes/article_layout.html
<div class="row p-2 my-2 shadow bg-body rounded">
  <div class="card p-2">
    <div class="card-header">
      <h3 class="card-title">
        <a class="navbar-brand" href="{% url 'board:article_detail' article.pk %}">
          {{ article.title }}
        </a>
      </h3>
      <a class="navbar-brand" href="{% url 'board:category' article.category.name %}">
        <span class="badge bg-secondary float-end">{{ article.category }}</span>
      </a>
      <small class="text-muted ms-1">
        <b>
          published by:
        </b>
        <span class="fst-italic">
        </span>
        <a href="{% url 'board:by_author' article.author %}">
          <span class="fst-italic">{{ article.author }}</span>
        </a>
        <b>
          on:
        </b>
        <span class="fst-italic">
          {{ article.dateCreation}}
        </span>
        </p>

      </small>
    </div>

    <div class="card-body">
      {% if article_list or article %}
      <p class="card-text ">{{ article.text|safe|truncatewords:25}}</p>
      {% else %}
      <p class="card-text ">{{ article.text|safe}}</p>
      {%endif%}

    </div>

    <div class="card-footer">

      {% if user.is_sign and article in user.article_set.all %}
      <a class="text-decoration-none" href="{% url 'board:response_list' article.pk %}">
        <button type="button" class="btn btn-outline-primary position-relative ">
          Responses
          <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger">
            {{ article.response_set.all|length }}
          </span>
        </button>
      </a>
      <a class="text-decoration-none" href="{% url 'board:article_update' article.pk %}">
        <button class="btn btn-outline-warning text-dark">
          Edit
        </button>
      </a>
      <a href="{% url 'board:article_delete' article.pk %}">
        <button class="btn btn-outline-danger">
          Delete
        </button>
      </a>
      {% else %}
      <a class="text-decoration-none" href="{% url 'board:response_create' article.pk %}">
        <button class="btn btn-outline-info">
          Respond
        </button>
      </a>
      {% endif %}
    </div>
  </div>
</div>

board/templates/board/includes/dashboard.html
{%include 'includes/svg_icons.html'%}
<div class="px-3 py-2 text-white">
  <div class="container">
    <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
      <a href="/" class="align-items-center my-2 my-lg-0 me-lg-auto text-white text-decoration-none">
        <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap">
          <!-- <use xlink:href="#bootstrap" /> -->
          <use xlink:href="#home" />
        </svg>
        Home
      </a>


      <ul class="nav col-12 col-lg-auto my-2 justify-content-center my-md-0 text-small">

        <li>
          <a href="{% url 'board:article_list' %}" class="nav-link text-white">
            <svg class="bi d-block mx-auto mb-1" width="24" height="24">
              <use xlink:href="#table" />
            </svg>
            Game Stock
          </a>
        </li>
        <li>
          <a href="{% url 'board:article_create' %}" class="nav-link text-white">
            <svg class="bi d-block mx-auto mb-1" width="24" height="24">
              <use xlink:href="#grid" />
            </svg>
            New Post
          </a>
        </li>
        <li>
          <a href="{% url 'board:dashboard' %}" class="nav-link text-white">
            <svg class="bi d-block mx-auto mb-1" width="24" height="24">
              <use xlink:href="#speedometer2" />
            </svg>
            Dashboard
          </a>
        </li>
        {% if user.is_superuser %}
        <li>
          <a href="/admin/" class="nav-link text-white">
            <svg class="bi d-block mx-auto mb-1" width="24" height="24">
              <use xlink:href="#grid" />
            </svg>
            Admin Panel
          </a>
        </li>

        {% endif %}

        <li>

          <a href="/auth/logout/" class="nav-link text-white">
            <svg class="bi d-block mx-auto mb-1" width="24" height="24">
              <use xlink:href="#people-circle" />
            </svg>
            Logout
          </a>
        </li>
      </ul>
    </div>
  </div>
</div>

board/templates/board/includes/navbar.html
{%include 'includes/svg_icons.html'%}

{% block nav %}

<nav class="container d-flex flex-column align-self-center  list-unstyled flex-md-row justify-content-between">
  <a href="/" class="align-self-center bi my-2 my-lg-0 me-lg-auto text-white text-decoration-none">
    <svg class=" me-2" width="40" height="32" role="img" aria-label="Bootstrap">
      <!-- <use xlink:href="#bootstrap" /> -->
      <use xlink:href="#home" />
    </svg>
    Home
  </a>


  <ul class="nav col-12 col-lg-auto my-2 justify-content-center my-md-0 text-small">

    <li>
      <a href="{% url 'board:article_list' %}" class="nav-link text-white">
        <svg class="bi d-block mx-auto mb-1" width="24" height="24">
          <use xlink:href="#table" />
        </svg>
        Board
      </a>
    </li>
  </ul>
  <ul class="d-flex list-unstyled">
    <li>
      <a href="{% url 'account_login' %}">
        <button type="button" class="btn btn-outline-info me-2 text-white">
          Login
        </button>
      </a>
    </li>
    <li>

      <a href="{% url 'account_signup' %}">
        <button type="button" class="btn btn-primary">
          Signup
        </button>
      </a>
    </li>
  </ul>

</nav>

{% endblock nav %}

board/templates/board/includes/response.html
<form method="POST" class="row g-3">
  {% csrf_token %}

  <div class="col-12">
    <h4 class="mb-4 mt-5">Your response:</h4>
    {{ form.text }}
  </div>

  <div class="col-12">
    <button type="submit" class="btn btn-primary">Send</button>
  </div>
</form>