MMORPGBB/urls.py

from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

from board.views import IndexView

urlpatterns = [
    path('', IndexView.as_view()),
    path('admin/', admin.site.urls),
    path('board/', include('board.urls')),
    path('auth/', include('sign.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

board/urls.py
from django.urls import path

from .views import *

app_name = 'board'
urlpatterns = [
    #article
    path('', ArticleList.as_view(), name='article_list'),
    path('<int:pk>', ArticleDetail.as_view(), name='article_detail'),
    path('create/', ArticleCreate.as_view(), name='article_create'),
    path('update/<int:article_pk>', ArticleUpdate.as_view(), name='article_update'),
    path('<int:article_pk>/delete/', ArticleDelete.as_view(), name='article_delete'),
    #response
    path('<int:article_pk>/response', ResponseList.as_view(), name='response_list'),
    path('<int:article_pk>/create_Response', ResponseCreate.as_view(), name='response_create'),
    path('<int:article_pk>/response/<int:response_pk>/accept', ResponseAccept.as_view(), name='response_accept'),
    path('<int:article_pk>/response/<int:response_pk>/reject', ResponseReject.as_view(), name='response_reject'),
    path('response/<int:response_pk>/delete', ResponseDelete.as_view(), name='response_delete'),
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
    #views  
    path('category/<slug:name>', CategoryView.as_view(), name='category'),
    path('by_author/<slug:name>', ByAuthorView.as_view(), name='by_author'),

]

sign/urls.py
from django.urls import path, include


urlpatterns = [
    path('', include('allauth.urls')),
]

board/models.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.contrib.auth import get_user_model
from django.db import models


User = get_user_model()

class Category(models.Model):
    name = models.CharField(max_length=32, unique=True)

    def __str__(self):
        return f'{self.name}'


class Article(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Author')
    dateCreation = models.DateTimeField(auto_now_add=True)
    title = models.CharField('Title', max_length=128)
    text = RichTextUploadingField('Text')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Category')

    def __str__(self):
        return f'{self.title}'


class Response(models.Model):
    author = models.OneToOneField(User, on_delete=models.CASCADE)
    text = models.TextField(max_length=1536)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    approved = models.BooleanField('Approved', null=True, blank=True)
    dateCreation = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.author}'
    #- {self.datetime}

board/forms.py
from ckeditor_uploader.widgets import CKEditorUploadingWidget
from django import forms

from .models import *


class ArticleCreateForm(forms.ModelForm):
    category = forms.ModelChoiceField(
        label='Category',
        widget=forms.Select(attrs={'class': 'form-select'}),
        queryset=Category.objects.all()
    )
    title = forms.CharField(label='Title', widget=forms.TextInput(attrs={'class': 'form-control'}))
    text = forms.CharField(label='Text', widget=CKEditorUploadingWidget(attrs={'class': 'form-control'}))

#    class Meta:
#        model = Article
#        exclude = ('author',)


class ResponseCreateForm(forms.ModelForm):
    text = forms.CharField(label='Text', widget=forms.Textarea(attrs={'class': 'form-control'}))

    class Meta:
        model = Response
        fields = ('text',)

board/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
# from django.core.mail import EmailMultiAlternatives
from django.shortcuts import render, redirect
# from django.template.loader import render_to_string
from django.urls import reverse
from django.views import View
from django.views.generic import ListView, CreateView, UpdateView, DetailView, DeleteView, TemplateView

from .forms import ArticleCreateForm, ResponseCreateForm
from .models import *
from .utils.permissions import IsAuthorMixin, NotIsAuthorMixin


class IndexView(LoginRequiredMixin, TemplateView):
    template_name = 'board/front.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        return context


class ArticleList(ListView):
    model = Article
    context_object_name = 'article_list'
    queryset = Article.objects.order_by('dateCreation')


class ArticleDetail(DetailView):
    model = Article
    context_object_name = 'article'


class ArticleCreate(LoginRequiredMixin, CreateView):
    model = Article
    form_class = ArticleCreateForm
    template_name = 'board/crud/article_create.html'

    def get_success_url(self):
        return reverse('board:article_list')

    def form_valid(self, form):
        article = form.save(commit=False)
        user = self.request.user
        article.author = user
        return super().form_valid(form)


class ArticleUpdate(IsAuthorMixin, UpdateView):
    model = Article
    pk_url_kwarg = 'Article_pk'
    form_class = ArticleCreateForm
    template_name = 'board/crud/article_create.html'

    def get_success_url(self):
        return reverse('board:article_list')

    def form_valid(self, form):
        messages.success(self.request, 'Success!')
        return super().form_valid(form)


class ArticleDelete(LoginRequiredMixin, DeleteView):
    model = Article
    template_name = 'board/crud/article_delete.html'
    success_url = '/board/'
    permission_required = 'board.article_delete'
    context_object_name = 'article'

    def get_object(self, **kwargs):
        article_id = self.kwargs.get('article_pk')
        article = Article.objects.get(pk=article_id)
        return article


class ResponseList(IsAuthorMixin, View):
    def get(self, request, *args, **kwargs):
        article_pk = kwargs['article_pk']
        article = Article.objects.get(pk=article_pk)
        rp = Response.objects.order_by('dateCreation').filter(article=article)

        context = {
            'response': rp,
            'article': article
        }

        return render(request, 'board/response_list.html', context)


class ResponseCreate(NotIsAuthorMixin, View):
    def get(self, request, **kwargs):
        form = ResponseCreateForm(request.ARTICLE or None)
        article = Article.objects.get(pk=kwargs['article_pk'])

        context = {
            'form': form,
            'article': article
        }

        return render(request, 'board/crud/response_create.html', context)

    def article(self, request, *args, **kwargs):
        form = ResponseCreateForm(request.ARTICLE)
        user = request.user
        article_pk = kwargs['article_pk']

        if form.is_valid():
            response = form.save(commit=False)
            response.author = user
            response.article = Article.objects.get(pk=article_pk)
            response.save()

        return redirect('board:article_list')


class ResponseAccept(IsAuthorMixin, View):
    def get(self, request, *args, **kwargs):
        response_pk = kwargs['response_pk']

        response = Response.objects.get(pk=response_pk)
        response.approved = True
        response.save()

        return redirect(request.META['HTTP_REFERER'])


class ResponseReject(IsAuthorMixin, View):
    def get(self, request, *args, **kwargs):
        response_pk = kwargs['response_pk']

        response = Response.objects.get(pk=response_pk)
        response.approved = False
        response.save()

        return redirect(request.META['HTTP_REFERER'])


class ResponseDelete(LoginRequiredMixin, DeleteView):
    model = Response
    template_name = 'board/crud/response_delete.html'
    success_url = '/board/'
    permission_required = ('board.response_delete')
    context_object_name = 'response'

    def get_object(self, **kwargs):
        response_id = self.kwargs.get('response_pk')
        response = Response.objects.get(pk=response_id)
        return response


class DashboardView(View):
    def get(self, request, *args, **kwargs):
        context = {
            'article': request.user.article_set.all(),
        }
        return render(request, 'board/dashboard.html', context)


class CategoryView(ListView):
    def get(self, request, *args, **kwargs):
        category = Category.objects.get(name=kwargs['name'])
        ar = Article.objects.order_by('dateCreation').filter(category=category)

        context = {
            'category': category,
            'article': ar,
        }

        return render(request, 'board/category_list.html', context)


class ByAuthorView(ListView):
    def get(self, request, *args, **kwargs):
        author = User.objects.get(username=kwargs['name'])
        ar = Article.objects.order_by('dateCreation').filter(author=author)

        context = {
            'author': author,
            'article': ar,
        }

        return render(request, 'board/by_author.html', context)

board/templates/board/article_detail.html
{% extends 'board/base.html' %}

{% block title %}
{{ article.title }} | {{article.category}}
{% endblock title %}

{% block content %}
<div class="container">
  {% include 'includes/article_layout.html'%}
</div>
{% endblock content %}

board/templates/board/article_list.html
{% extends 'board/base.html' %}

{% block title %}Board | All Article{% endblock title %}

{% block content %}

<div class="container">
  {% for article in article_list %}
  {% include 'includes/article_layout.html'%}

  {% empty %}
  <div class="text-center">
    <h3 class="fw-bold">No article yet</h3>
    <p class="lead ">Start posting!</p>
    <a href="{% url 'board:article_create' %}">
      <button type="button" class="btn btn-primary btn-lg px-4 gap-3">
        Add New Article
      </button>
    </a>
  </div>
  {% endfor %}
</div>

{% endblock content %}

board/templates/board/base.html
{% load i18n %}
{% load static %}

<!DOCTYPE html>
<html>

<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <!-- Favicons -->
  <link rel="apple-touch-icon" href="{% static 'img/favicons/favicon-96x96.png' %}" sizes="96x96">
  <link rel="icon" href="{% static 'img/favicons/favicon-32x32.png' %}" sizes="32x32" type="image/png">
  <link rel="icon" href="{% static 'img/favicons/favicon-16x16.png' %}" sizes="16x16" type="image/png">

  <link rel="icon" href="{% static 'img/favicons/favicon.ico' %}">
  <meta name="theme-color" content="#7952b3">

  <link href="{% static 'css/style.css' %}" rel="stylesheet" />


  <script defer src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
    integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous">
    </script>
  <script defer src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
    integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous">
    </script>

  <!-- <script defer src="offcanvas.js"></script> -->
  <script defer src="{% static 'js/script.js' %}"></script>
  <title>
    {% block title %}
    {% endblock title %}

  </title>

</head>

<body>
  <header class="site-header sticky-top py-1">


    {%if user.is_sign %}

    {% include 'includes/dashboard.html' %}
    {% else%}
    {% include 'includes/navbar.html' %}

    {%endif%}

  </header>

  <main>
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-success" role="alert">{{ message }}</div>
    {% endfor %}
    {% endif %}

    {% block content %}
    {% endblock content %}

</body>

</html>

board/templates/board/by_author.html
{% extends 'board/base.html' %}
{% block title %}
{{author}}
{% endblock title %}

{% block content %}

{% for article in article %}
<div class="container">
  {%include "includes/article_layout.html"%}
</div>
{%endfor%}
{% endblock content %}

board/templates/board/category_list.html
{% extends 'board/base.html' %}
{% block title %}
{{category}}
{% endblock title %}

{% block content %}

{% for article in article %}
<div class="container">
  {%include "includes/article_layout.html"%}
</div>
{%endfor%}
{% endblock content %}

board/templates/board/dashboard.html
{% extends 'board/base.html' %}

{% block title %}
Dashboard
{% endblock title %}

{% block content %}
<div class="container">

  {% for article in article %}
  <div class="row">
    {%include "includes/article_layout.html" %}
  </div>
  {% endfor %}

</div>
{% endblock content %}

board/templates/board/front.html
{% extends 'board/base.html' %}
{% block title %}
Board
{% endblock title %}

{% block content %}

<div class="position-relative overflow-hidden p-3 p-md-5 m-md-3 text-center bg-light">
  <div class="col-md-5 p-lg-5 mx-auto my-5">
    <h1 class="display-4 fw-normal">Board</h1>
    <p class="lead fw-normal">
      You can exchange your game assets here
    </p>
    <a class="btn btn-outline-secondary" href="{% url 'board:article_list' %}">Let's start</a>
  </div>
  <div class="product-device shadow-sm d-none d-md-block"></div>
  <div class="product-device product-device-2 shadow-sm d-none d-md-block"></div>
</div>

<!-- <div class="d-md-flex flex-md-equal w-100 my-md-3 ps-md-3">
  <div class="bg-dark me-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center text-white overflow-hidden">
    <div class="my-3 py-3">
      <h2 class="display-5">Another headline</h2>
      <p class="lead">And an even wittier subheading.</p>
    </div>
    <div class="bg-light shadow-sm mx-auto" style="width: 80%; height: 300px; border-radius: 21px 21px 0 0;"></div>
  </div>
  <div class="bg-light me-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center overflow-hidden">
    <div class="my-3 p-3">
      <h2 class="display-5">Another headline</h2>
      <p class="lead">And an even wittier subheading.</p>
    </div>
    <div class="bg-dark shadow-sm mx-auto" style="width: 80%; height: 300px; border-radius: 21px 21px 0 0;"></div>
  </div>
</div>

<div class="d-md-flex flex-md-equal w-100 my-md-3 ps-md-3">
  <div class="bg-light me-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center overflow-hidden">
    <div class="my-3 p-3">
      <h2 class="display-5">Another headline</h2>
      <p class="lead">And an even wittier subheading.</p>
    </div>
    <div class="bg-dark shadow-sm mx-auto" style="width: 80%; height: 300px; border-radius: 21px 21px 0 0;"></div>
  </div>
  <div class="bg-primary me-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center text-white overflow-hidden">
    <div class="my-3 py-3">
      <h2 class="display-5">Another headline</h2>
      <p class="lead">And an even wittier subheading.</p>
    </div>
    <div class="bg-light shadow-sm mx-auto" style="width: 80%; height: 300px; border-radius: 21px 21px 0 0;"></div>
  </div>
</div>

<div class="d-md-flex flex-md-equal w-100 my-md-3 ps-md-3">
  <div class="bg-light me-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center overflow-hidden">
    <div class="my-3 p-3">
      <h2 class="display-5">Another headline</h2>
      <p class="lead">And an even wittier subheading.</p>
    </div>
    <div class="bg-body shadow-sm mx-auto" style="width: 80%; height: 300px; border-radius: 21px 21px 0 0;"></div>
  </div>
  <div class="bg-light me-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center overflow-hidden">
    <div class="my-3 py-3">
      <h2 class="display-5">Another headline</h2>
      <p class="lead">And an even wittier subheading.</p>
    </div>
    <div class="bg-body shadow-sm mx-auto" style="width: 80%; height: 300px; border-radius: 21px 21px 0 0;"></div>
  </div>
</div>

<div class="d-md-flex flex-md-equal w-100 my-md-3 ps-md-3">
  <div class="bg-light me-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center overflow-hidden">
    <div class="my-3 p-3">
      <h2 class="display-5">Another headline</h2>
      <p class="lead">And an even wittier subheading.</p>
    </div>
    <div class="bg-body shadow-sm mx-auto" style="width: 80%; height: 300px; border-radius: 21px 21px 0 0;"></div>
  </div>
  <div class="bg-light me-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center overflow-hidden">
    <div class="my-3 py-3">
      <h2 class="display-5">Another headline</h2>
      <p class="lead">And an even wittier subheading.</p>
    </div>
    <div class="bg-body shadow-sm mx-auto" style="width: 80%; height: 300px; border-radius: 21px 21px 0 0;"></div>
  </div>
</div> -->
{% endblock content %}

board/templates/board/response_list.html
{% extends 'board/base.html' %}
{% block title %}
{{ article.title }} | {{article.category}}
{% endblock title %}

{% block content %}
<div class="container">
  <div class="card p-2">
    <div class="card-header">
      <h3 class="card-title">
        <a class="navbar-brand" href="{% url 'board:article_detail' article.pk %}">
          {{ post.title }}
        </a>
      </h3>
      <a class="navbar-brand" href="{% url 'board:article_detail' article.pk %}">
        <span class="badge bg-secondary float-end">{{ article.category }}</span>
      </a>
      <small class="text-muted ms-1">
        <b>
          published by:
        </b>
        <span class="fst-italic">
        </span>
        <a href="{% url 'board:by_author' article.author %}">
          <span class="fst-italic">{{ article.author }}</span>
        </a>
        <b>
          on:
        </b>
        <span class="fst-italic">
          {{ article.dateCreation}}
        </span>
        </p>
      </small>
    </div>

    <div class="card-body">
      <p class="card-text ">{{ article.text|safe|truncatewords:50}}</p>
    </div>
  </div>

  {% for response in response %}
  <div class="shadow-sm p-3 my-2 bg-body rounded">
    <div class="d-flex justify-content-between p-1">
      <a href="{% url 'board:by_author' response.author %}">

        <h5 class="mb-1">{{ response.author }}</h5>

      </a>
      <small class="text-muted">Submitted on: {{ response.dateCreation }}</small>
    </div>
    <div class="row">
      <div class="col-lg-10 col-sm-12">
        <p class="ms-3">{{ response.text }}</p>
      </div>

      <div class="col-lg-2 col-sm-12">
        <div class="d-flex flex-md-row flex-lg-column align-items-lg-end  justify-content-end gap-1">
          {% if response.approved %}

          <button class="btn btn-outline-success">
            Accepted
          </button>
          {%else %}
          <a href="{% url 'board:response_accept' article.pk response.pk %}">
            <button class="btn btn-success">
              Accept
            </button>
          </a>
          {% endif %}

          {% if not response.approved and not response.approved is None %}

          <button class="btn btn-outline-warning text-dark">
            Rejected
          </button>
          {%else%}
          <a href="{% url 'board:response_reject' article.pk response.pk %}">
            <button class="btn btn-warning">
              Reject
            </button>
          </a>
          {% endif %}
          <a href="{% url 'board:response_delete' response.pk %}">
            <button class="btn btn-danger">
              Delete
            </button>
          </a>

        </div>
      </div>
    </div>
  </div>
  {% empty %}
  <div class="text-center">
    <h3 class="fw-bold">No response yet</h3>
    <p class="lead ">Check later and keep posting!</p>
    <a href="{% url 'board:article_list' %}">
      <button type="button" class="btn btn-primary btn-lg">
        To Board
      </button>
    </a>
  </div>
</div>



{% endfor %}


{% endblock content %}